# The range() function may also accept three arguments – take a look at the code in the editor.
for i in range(2, 8, 3):
    print("The value of i is currently", i)

# Note: if the set generated by the range() function is empty, the loop won't execute its body at all.
for i in range(1, 1):
    print("The value of i is currently", i)

# Let's have a look at a short program whose task is to write some of the first powers of two:
power = 1
for expo in range(16):
    print("2 to the power of", expo, "is", power)
    power *= 2
